### ISSUE TITLE
Hell Wind starts attack run way too early

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#213]
![opene2140_hellwind_incorrect_attack_run2](https://github.com/OpenE2140/OpenE2140/assets/119738087/7f14c0e5-d0ba-4291-a1ea-b8ce9be49928)

**Comment by Dzierzan** [comment]
This issue is not that straight forward due to how gravity bomb works in ORA. Hellwind starts dropping bombs as soon as a target is in weapon's range.

I could decrease the range and decrease burstdelay as well and see how this works out. 

Mind that in ORA mods, gravity bombs use forward force, which I also applied it here, it's just not that visable at once. I might tweak it better.
