### ISSUE TITLE
Flip Heavy Tech building back

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#457]
Heavy Tech sprite was flipped in the game, but in in-game database and manual (and even the icon in production sidebar) it's the correct version:

![Image](https://user-images.githubusercontent.com/119738087/265139340-404f2c12-d837-418b-bea5-b27c87a12bcd.png)

Tasks:
- [ ] flip the sprite (in sequences)
- [ ] update elevator offset
- [ ] experiment with footprint: original or `=xx =xx ===` (or different)
- [ ] create "patch" sprite that:
  - [ ] removes the shadow on the left side (see screenshot below)
  - [ ] adds new shadow on the right side (see screenshot below)

Edited screenshot:
![edited_screenshot](https://cdn.discordapp.com/attachments/1080437046004424768/1147303207505231883/Screenshot_20230902_005335.png)

**Comment by Dzierzan** [comment]
I am sorry but I misunderstood you on Discord. I thought you want to correct the icon, not the whole sprite.

I refuse doing that. It may be flipped, but i strongly believe it was the intentional decision of developers to make it like that in order to make the building not that similar to the HQ. 

Besides, notice that the lighting of current model matches the shadow, so i would have to put a lot work to change lighting.

So sorry, I am forced to close this one.

The only thing I can do is updating the icon itself, so at least the main sprite will be consistent with the icon.
